### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by chencc5956** [liuqk3/PUT#13]
您好，非常感谢您的论文，给了我很大启发。我在复现代码的过程中发生了一些问题。
①我是想做一个简单的测试，所以只用了一张celeba-hq里的图片和一张mask图片进行测试，不知道是不是因为数据的存放路径有问题，一直是显示这个error。请问可以帮忙解惑吗？

![image](https://user-images.githubusercontent.com/51091956/197337803-a63b3127-7371-4b23-88d4-9e436e028e2b.png)

②另外，一直没有找到scripts文件夹里/tools/dataset_tool.py这个文件。

谢谢您！！！

**Comment by liuqk3** [comment]
Thanks for your interests!

You should change the configurations for you validation data. The `name` and `image_list_file` are the key to find the image correctly.

https://github.com/liuqk3/PUT/blob/7de8ce0ada1e63e8c5300857a463d68380e142f0/configs/put_cvpr2022/ffhq/transformer_ffhq.yaml#L115
https://github.com/liuqk3/PUT/blob/7de8ce0ada1e63e8c5300857a463d68380e142f0/configs/put_cvpr2022/ffhq/transformer_ffhq.yaml#L116

**Comment by chencc5956** [comment]
OK, I solved this problem. Thanks for your help.
