### ISSUE TITLE
推理有问题

### ISSUE THREAD

**Issue by zhangshilong2000** [liuqk3/PUT#23]
![image](https://github.com/liuqk3/PUT/assets/72057128/75aaf3d3-df95-4cc5-aff9-739d1b03a7d3)
![image](https://github.com/liuqk3/PUT/assets/72057128/1a6bbec5-ea3f-483b-aaaf-6b4006b71e21)
你好，推理文件中出现引用包错误，导致程序不能执行，这个错误可能是由什么引起的？

**Comment by liuqk3** [comment]
应该是没有编译PUT。建议仔细阅读readme中的安装步骤。另外，我是用vscode写的代码，而pycharm有时候会自动处理一些路径问题，也可以进一步排查是否pycharm引起的。
