### ISSUE TITLE
#推理问题

### ISSUE THREAD

**Issue by zhangshilong2000** [liuqk3/PUT#24]
![image](https://github.com/liuqk3/PUT/assets/72057128/a9ea76dd-89a0-46b0-ab01-3002c644bd4a)
您好，这个问题有可能是什么引起的？

**Comment by liuqk3** [comment]
这个问题是因为在给定的路径下没有找到图片或者mask，需要仔细看下路径是否正确。另外，最好先将数据软连接到./PUT目录下，然后测试的时候用相对路径而不是绝对路径。
