### ISSUE TITLE
推理问题

### ISSUE THREAD

**Issue by superlittl** [liuqk3/PUT#28]
同样的困扰，
![图片](https://github.com/liuqk3/PUT/assets/105760324/81eea4ce-e30e-404c-a327-a667af97f1f2)
请问您提到的绝对路径是指哪里，
![图片](https://github.com/liuqk3/PUT/assets/105760324/e226d9c2-25ee-4b55-bd48-01ab6ae37ccc)
我觉得还是这个图片路径读取不到，

**Comment by liuqk3** [comment]
首先，需要按照`readme/install_instruction.sh`进行安装；然后，建议使用`scripts/inference_inpainting.py`脚本，路径指的就是image_dir和mask_dir。另外，建议将目录软连接到project的目录，并指定相对路径。

使用示例可以参考`scripts/inference_inpainting.sh`中的使用方式。
