### ISSUE TITLE
How to select the best model for testing?

### ISSUE THREAD

**Issue by LonglongaaaGo** [liuqk3/PUT#3]
Hi @liuqk3,
Thank you so much for your awesome work.
Can you give some insights on how to select the best model for P-VQVAE and UQ-transformer during training? I found the input image is also masked for P-VQVAE, so fid, lpips would not correct when we directly use the masked gt and reconstructed image.

**Comment by liuqk3** [comment]
Thanks for your intrests in our work. We do not select the best model. In our experiments, we just set the maximum number of epochs and get the final trained model. According to my experience, the more steps the model is trained, the better the performance you will get.

**Comment by LonglongaaaGo** [comment]
> Thanks for your intrests in our work. We do not select the best model. In our experiments, we just set the maximum number of epochs and get the final trained model. According to my experience, the more steps the model is trained, the better the performance you will get.

Wow, that's really cool. Thank you so much!
