### ISSUE TITLE
依赖关系不可用

### ISSUE THREAD

**Issue by LiaoYuWei1** [liuqk3/PUT#38]
用项目中的requirements.txt来pip相应的包，依赖关系对应不上

**Comment by liuqk3** [comment]
感谢关注我们的工作。请问是按照readme中的说明进行安装的吗？具体的错误信息能否提供下？

**Comment by LiaoYuWei1** [comment]
> 感谢关注我们的工作。请问是按照readme中的说明进行安装的吗？具体的错误信息能否提供下？

你好，感谢答复，readme里面好像没有涉及到环境相关的说明，我是在python3.8的pip install -r requirements.txt就出现报错了
![pip_error](https://github.com/liuqk3/PUT/assets/116809364/775c9b61-ccfb-48f5-bbda-f7281926ddbb)

**Comment by liuqk3** [comment]
请参考readme中指出的这个文件进行安装：https://github.com/liuqk3/PUT/blob/dbd10440c735fb643e5f285b87ca46ad5fe83764/README.md?plain=1#L52

**Comment by LiaoYuWei1** [comment]
> 请参考readme中指出的这个文件进行安装：
> 
> https://github.com/liuqk3/PUT/blob/dbd10440c735fb643e5f285b87ca46ad5fe83764/README.md?plain=1#L52

你好，我用该文件进行环境安装还是会出现依赖关系报错
![image](https://github.com/liuqk3/PUT/assets/116809364/775e6b64-a33d-4386-b337-5d0206f12742)

**Comment by liuqk3** [comment]
降低kornia版本不影响模型的测试和训练。比如0.5版本。

**Comment by LiaoYuWei1** [comment]
> 降低kornia版本不影响模型的测试和训练。比如0.5版本。
好嘞，谢谢老哥

**Comment by LiaoYuWei1** [comment]
> 降低kornia版本不影响模型的测试和训练。比如0.5版本。

你好，我还想请问一下如果不跑训练只跑测试的话，也需要cuda环境吗

**Comment by liuqk3** [comment]
> > 降低kornia版本不影响模型的测试和训练。比如0.5版本。
> 
> 你好，我还想请问一下如果不跑训练只跑测试的话，也需要cuda环境吗

可以，但是速度比较慢，可以试一下。
