### ISSUE TITLE
关于环境的问题

### ISSUE THREAD

**Issue by tanbuzheng** [liuqk3/PUT#41]
作者您好！
想请问，您的所有代码都可以在pytorch1.7.1下实现么？
我在安装虚拟环境时出现问题，因为kornia==0.6.11总是与pytorch1.7.1不匹配，想问您是怎么解决这个问题的？

期待您的回复！

**Comment by liuqk3** [comment]
对于公开的代码，kornia可能不是必须的，可以先不安装kornia试试。

**Comment by tanbuzheng** [comment]
好的谢谢！，想请问在本文的任务中，kornia是用什么？

**Comment by tanbuzheng** [comment]
好的谢谢

**Comment by tanbuzheng** [comment]
您好，我想再问问您，项目里的两片论文的预训练模型均是在pytorch1.7.1+cuda10.1下被测试么？我的gpu，cuda版本较高，pytorch>1.10, cuda>11能否满足条件？我看您在文件说明中，注释掉了这个pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 -f https://download.pytorch.org/whl/torch_stable.html，这个环境配置是否与预训练模型匹配？

**Comment by liuqk3** [comment]
我训练的时候，没有特别在意torch版本，因为需要的计算资源较大，所以需要在不同的机器上跑实验。不同机器的环境也是根据硬件环境来选择torch版本。印象中，1.5-2.0之间的版本都有可能用过。我的经验来看，只要能训练且loss正常下降，则没问题。
