### ISSUE TITLE
vit_base和p-vqvae模型区别

### ISSUE THREAD

**Issue by wangupupup** [liuqk3/PUT#42]
您好！请问您提供的预训练模型中，我看有tpami2024_vit_base_ffhq_res256和tpami2024_p_vqvae_imagenet_res256,这两个有什么区别吗？

**Comment by wangupupup** [comment]
哦哦我应该明白了 就是不同阶段（p_vqvae和uq-transformer）的对应的模型？

**Comment by liuqk3** [comment]
是的。uq-transformer即是最终的inpainting模型。
