### ISSUE TITLE
places2数据集指标

### ISSUE THREAD

**Issue by wangupupup** [liuqk3/PUT#43]
您好，请问可以提供places2数据集（分辨率为256*256）在10%-20%、20%-30%、30%-40%、40%-50%分别的指标吗？我本来想自己测试，但我看代码中对于places2数据集好像只是取了一些子集进行训练的，所以不知道在这些子集中哪些作为训练或测试的。
![image](https://github.com/user-attachments/assets/fa5c6431-dd12-42c2-9a81-a29a63cf90f7)

**Comment by liuqk3** [comment]
感谢关注我们的工作。上面列出的子路径都是用来训练的。places2下面有个val路径，这个是用来测试的。

**Comment by wangupupup** [comment]
感谢回复，我看到了data下面的文件，我想这就是train和val的数据，我将用val图像做在10%-20%、20%-30%、30%-40%、40%-50%mask的指标。
![image](https://github.com/user-attachments/assets/ce6b4ad9-c2b9-4499-9dd8-87dba6e9b806)

**Comment by liuqk3** [comment]
可以的。只需要准备好对应的mask就行了。

**Comment by wangupupup** [comment]
好的 明白了 感谢回答！
