### ISSUE TITLE
微调的问题

### ISSUE THREAD

**Issue by wangupupup** [liuqk3/PUT#44]
作者您好！我现在想基于您提供的ffhq模型上对一个仅有500张的小数据集进行微调，我在想第一阶段vqvae是完全可以的，但是在第二阶段中我一是要在配置文件中写我自己微调的第一阶段的模型路径，还要加载您提供的在ffhq数据集上的uq-transformer模型，但我看代码感觉这个在ffhq上预训练的uq-transformer模型会覆盖掉我自己微调的第一阶段的模型啊，是这样吗？

**Comment by liuqk3** [comment]
是这样的。我之前在训练第二阶段的UQ-Transformer的时候，是也保存了P-VQVAE的权重。所以在加载UQ-Transformer的时候，会覆盖之前加载的P-VQVAE权重。你可以直接把UQ-Transformer中的P-VQVAE权重删除，这样就不会覆盖你自己训练的P-VQVAE了。

**Comment by wangupupup** [comment]
感谢回复，我看了代码，发现正好有删除P-VQVAE的权重的函数：
![image](https://github.com/user-attachments/assets/a5328377-8baa-48bb-8e61-429d9890d229)
所以我尝试先加载P-VQVAE权重（配置文件的P-VQVAE下的params中配置ckpt_path） 再加载UQ-Transformer权重的时候删除P-VQVAE的权重（只需要在配置文件中在model的params加入ckpt_path就可以，之前配置文件中没有此参数）  然后再在train_net.py中不让他resume（resume的话又会覆盖权重）  感觉这样就可以实现第二阶段在预训练UQ-Transformer的微调了
