### ISSUE TITLE
关于训练加载数据的问题

### ISSUE THREAD

**Issue by ShengJinhao** [liuqk3/PUT#45]
作者您好，我在训练的时候，更换自己准备的数据集，改了yaml文件的配置，但是我在进行训练的时候出现了 ModuleNotFoundError: No module named 'image_synthesis.data.utils.imagenet_utils'问题。
<img width="939" alt="截屏2024-09-12 18 17 02" src="https://github.com/user-attachments/assets/175c9fa7-f28e-4284-a84b-daf041772a64">
这是ImageListDataset不支持的表现吗还是？麻烦您看到回复一下，谢谢您。

**Comment by liuqk3** [comment]
Just commnet the 11th line in image_synthesis/data/image_list_dataset.py is OK. The codes been updated to fix this bug.
