### ISSUE TITLE
About the pretained model of ImageNet from BaiduYunpan

### ISSUE THREAD

**Issue by Haoru** [liuqk3/PUT#8]
The pretrained model of ImageNet from BaiduYunpan is missing. Could you please provide it again? And it is difficult for me to download the pretrained model of ImageNet from OneDrive completely.

**Comment by liuqk3** [comment]
Hi @Haoru ,

The pretrained models have been re-uploaded to BaiduYunPan. You can download them now.

**Comment by Haoru** [comment]
Thank you very much! And how to set parameters for the evaluation of image inpainting methods that only produce one deterministic result for the given input?
