### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by Jackieqfh143** [liuqk3/PUT#9]
When testing on placenatual, we got the following error. Any idea about that?
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
Perhaps, the pretrained file is broken?

**Comment by liuqk3** [comment]
Hi @Jackieqfh143 ,
Thanks for your interests!

Where did you download the models? A few days ago, I re-uploaded the models on BaiduYunPan. You can test them.

**Comment by Jackieqfh143** [comment]
Thanks for your reply. I was downloading the checkpoint from dropbox, but it's broken. Now it is working using the model from BaiduYun. Thanks.
